# Generated by Django 5.2.7 on 2025-11-03 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("position", models.JSONField(blank=True, default=dict, null=True)),
                ("rotation", models.FloatField(blank=True, default=0, null=True)),
                ("skin", models.IntegerField(blank=True, default=0, null=True)),
                ("interior", models.IntegerField(blank=True, default=0, null=True)),
                ("dimension", models.IntegerField(blank=True, default=0, null=True)),
                ("team", models.CharField(blank=True, max_length=50, null=True)),
                ("health", models.IntegerField(blank=True, default=0, null=True)),
                ("money", models.IntegerField(blank=True, default=0, null=True)),
                ("weapons", models.JSONField(blank=True, default=dict, null=True)),
                ("armor", models.FloatField(blank=True, default=0, null=True)),
                ("clothes", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="player",
                    ),
                ),
            ],
            options={
                "db_table": "userdata",
            },
        ),
    ]
