# Generated by Django 5.2.7 on 2025-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdata",
            name="ammo",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="weapons",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
