# Generated by Django 5.2.7 on 2025-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_playerdata_ammo_alter_playerdata_weapons"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdata",
            name="weapons_in_hand",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
