# Generated by Django 5.2.7 on 2025-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_playerdata"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="playerdata",
            table="tb_player_data",
        ),
    ]
