# Generated by Django 5.2.7 on 2025-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_alter_playerdata_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdata",
            name="wantedlevel",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
