# Generated by Django 5.2.7 on 2025-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_playerdata_weapons_in_hand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdata",
            name="ammo",
            field=models.JSONField(blank=True, default=[[]], null=True),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="weapons",
            field=models.JSONField(blank=True, default=[[]], null=True),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="weapons_in_hand",
            field=models.JSONField(blank=True, default=[[]], null=True),
        ),
    ]
