# Generated by Django 5.2.7 on 2025-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0004_playerdata_wantedlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdata",
            name="armor",
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="clothes",
            field=models.JSONField(
                blank=True,
                default=[
                    [
                        ["vestblack", "vest", 0],
                        ["player_face", "head", 1],
                        ["jeansdenim", "jeans", 2],
                        ["sneakerbincblk", "sneaker", 3],
                    ]
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="health",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="position",
            field=models.JSONField(
                blank=True, default=[[-1969.4, 137.85, 27.69]], null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdata",
            name="team",
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
