# Generated by Django 5.2.7 on 2025-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_alter_playerdata_armor_alter_playerdata_clothes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdata",
            name="weapons",
            field=models.JSONField(blank=True, default=[[]], null=True),
        ),
    ]
